#coding:utf-8

BAD_REQUEST = 1000
BUCKET_NOT_FOUND = 1001
OBJECT_NOT_FOUND = 1002
OBJECT_SAVE_FAILED = 1003

MESSAGE = {
    BAD_REQUEST: "BAD REQUEST",
    BUCKET_NOT_FOUND : "BUCKET NOT FOUND",
    OBJECT_NOT_FOUND : "OBJECT NOT FOUND",
    OBJECT_SAVE_FAILED : "FAILED TO SAVE OBJECT",
}